# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6CyJbqchsIeLN7xfsCP214wvoRx0mCj
"""

a=int(input("Enter price of 1st object"))
b=int(input("Enter price of 2nd object"))
c=int(input("Enter price of 3rd object"))
n1=int(input("Enter quantity of 1st object"))
n2=int(input("Enter quantity of 2nd object"))
n3=int(input("Enter quantity of 3rd object"))
t=(a*n1)+(b*n2)+(c*n3)
if(t>50):
  t=(t*9)/10
print(f"{t:.2f}")

